# Generated by Django 5.0.6 on 2025-06-22 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shared", "0002_alter_auditlog_resource_id"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="auditlog",
            name="audit_logs_user_id_fbfd51_idx",
        ),
        migrations.RemoveIndex(
            model_name="auditlog",
            name="audit_logs_action_391715_idx",
        ),
        migrations.RemoveIndex(
            model_name="auditlog",
            name="audit_logs_resourc_bda8a6_idx",
        ),
        migrations.RemoveIndex(
            model_name="auditlog",
            name="audit_logs_ip_addr_b969fa_idx",
        ),
    ]
